### ISSUE TITLE
rest-client issue on server

### ISSUE THREAD

**Issue by rajkrgoyal** [ronakjain90/paytm#1]
It's working fine on localhost in test mode. On production I am getting rest client 403 forbidden error.

**Comment by rajkrgoyal** [comment]
Hi, One thing I want to make sure, merchant-guid would be same for test and production both?

**Comment by ronakjain90** [comment]
You'd need to confirm that with Paytm support. Your issue seems to be a configuration issue. Please try to get correct keys for your account.

**Comment by rajkrgoyal** [comment]
Thanks! It worked!
